import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Header from "@/component/header";
import Footer from "@/component/footer";
import "./globals.css";
import { dir } from "i18next";
import { ReactNode } from "react";

const languages = ["en", "zh"];

type Props = {
  children: ReactNode;
  params: { lng: string };
};
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<Props>) {
  console.log(lng, "lng");
  return (
    <html lang={lng}>
      {/* dir={dir(lng)} */}
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Header />
          {children}
          <Footer />
        </AntdRegistry>
      </body>
    </html>
  );
}
